version: "3.9"

services:
  api:
    build:
      context: .
    container_name: housing-api-api-1
    command: python app.py
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: housing_db
      DB_USER: matheo
      DB_PASSWORD: u6x5qhup
      DB_PORT: 5432

  db:
    image: postgres:15
    container_name: housing-api-db-1
    environment:
      POSTGRES_USER: matheo
      POSTGRES_PASSWORD: u6x5qhup
      POSTGRES_DB: housing_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
