services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: housing_db
      POSTGRES_USER: matheo
      POSTGRES_PASSWORD: u6x5qhup
    ports:
      - "5432:5432"
